;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-paren
	c-electric-semi&comma
	c-electric-star
	c-indent-line-or-region
	c-indent-new-comment-line
	c-up-conditional
	downcase-region
	drag-stuff-right
	kill-region
	upcase-region
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	c-electric-slash
	comment-region
	goto-line
	overwrite-mode
	))
